# Generated by Django 4.1.4 on 2023-01-01 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_date_end_alter_task_date_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_end',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date_start',
            new_name='start_date',
        ),
    ]
