# Generated by Django 4.1.4 on 2023-01-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_date_end_task_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('O', 'open'), ('P', 'in progress'), ('C', 'closed')], default='O', max_length=1),
        ),
    ]
